# Generated by Django 4.2.30 on 2026-07-29 22:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionCabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='SGI-P-16/R-03', editable=False, max_length=50)),
                ('revision', models.IntegerField(default=16, editable=False)),
                ('tipo_inspeccion', models.CharField(choices=[('Formal', 'Formal'), ('Informal', 'Informal')], default='Formal', max_length=20)),
                ('faena', models.CharField(max_length=150, verbose_name='Faena')),
                ('lugar', models.CharField(max_length=250, verbose_name='Lugar')),
                ('fecha_inspeccion', models.DateField(blank=True, null=True, verbose_name='Fecha de Inspección')),
                ('hora_inspeccion', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('realizada_por', models.CharField(max_length=150, verbose_name='Realizada por')),
                ('notificado_a', models.CharField(max_length=150, verbose_name='Notificado a')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hora_creacion', models.TimeField(auto_now_add=True)),
                ('correo_usuario_creador', models.EmailField(max_length=50, verbose_name='Correo Usuario Creador')),
                ('firma_responsable', models.FileField(blank=True, null=True, upload_to='firma_inspecciones/', verbose_name='Firma Responsable')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Inspección (Cabecera)',
                'verbose_name_plural': 'Inspecciones (Cabeceras)',
                'ordering': ['-fecha_inspeccion'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(verbose_name='N° Ítem')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('grado_riesgo', models.CharField(choices=[('A', 'A: ALTO'), ('B', 'B: MEDIO'), ('C', 'C: LEVE')], max_length=1, verbose_name='Grado de Riesgo')),
                ('recomendaciones', models.TextField(verbose_name='Recomendaciones')),
                ('responsable_accion', models.CharField(max_length=150, verbose_name='Nombre Responsable')),
                ('fecha_cumplimiento', models.DateField(verbose_name='Fecha Límite de Cumplimiento')),
                ('cumplimiento', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=10, verbose_name='Estado de Cumplimiento')),
                ('evidencia_cierre', models.FileField(blank=True, null=True, upload_to='evidencias_inspecciones/', verbose_name='Archivo de Evidencia')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se cerró')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_reportes.inspeccioncabecera')),
            ],
            options={
                'verbose_name': 'Ítem de Inspección',
                'verbose_name_plural': 'Ítems de Inspección',
                'ordering': ['numero_item'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionConducta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_trabajo', models.CharField(max_length=250, verbose_name='Área de Trabajo')),
                ('persona_observada', models.CharField(max_length=200, verbose_name='Persona Observada')),
                ('fecha_observacion', models.DateField(verbose_name='Fecha de Observación')),
                ('descripcion_tarea', models.TextField(verbose_name='Descripción de la Tarea')),
                ('observacion', models.TextField(verbose_name='Descripción de la Observación')),
                ('antiguedad_puesto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antigüedad en el Puesto')),
                ('tarea', models.CharField(max_length=250, verbose_name='Tarea')),
                ('observacion_planificada', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=20)),
                ('mejora', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hora_creacion', models.TimeField(auto_now_add=True)),
                ('nombre_usuario_creador', models.CharField(max_length=150, verbose_name='Usuario Creador')),
                ('correo_usuario_creador', models.EmailField(max_length=50, verbose_name='Correo Usuario Creador')),
                ('firma_creador', models.FileField(blank=True, null=True, upload_to='firma_obsconducta/', verbose_name='Firma Responsable')),
                ('firma_observado', models.FileField(blank=True, null=True, upload_to='firma_obsconducta/', verbose_name='Firma Responsable')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_exportado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Exportación a PDF.')),
                ('hora_exportado', models.TimeField(blank=True, null=True, verbose_name='Hora de Exportación a PDF.')),
            ],
            options={
                'verbose_name': 'Observación de Conducta',
                'verbose_name_plural': 'Observaciones de Conductas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteHSGI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('centro_trabajo', models.CharField(max_length=150, verbose_name='Centro de Trabajo/Obra')),
                ('fecha_hallazgo', models.DateField(verbose_name='Fecha del Hallazgo')),
                ('hora_hallazgo', models.TimeField(verbose_name='Hora del Hallazgo')),
                ('turno', models.CharField(max_length=50, verbose_name='Turno')),
                ('proceso_hallazgo', models.CharField(max_length=250, verbose_name='Proceso del Hallazgo')),
                ('actividad_involucrada', models.CharField(max_length=250, verbose_name='Actividad Involucrada')),
                ('lugar_especifico', models.CharField(max_length=250, verbose_name='Lugar Específico')),
                ('ambito_hallazgo', models.CharField(max_length=250, verbose_name='Ámbito del Hallazgo')),
                ('causa', models.TextField(verbose_name='Causa del Hallazgo')),
                ('nivel_hallazgo', models.CharField(max_length=50, verbose_name='Nivel del Hallazgo')),
                ('supervisor_hallazgo', models.CharField(max_length=150, verbose_name='Supervisor del Hallazgo')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('descripcion_hallazgo', models.TextField(verbose_name='Descripción del Hallazgo')),
                ('accion_inmediata', models.TextField(verbose_name='Acción Inmediata/Correctivas')),
                ('responsable_cierre', models.CharField(max_length=150, verbose_name='Responsable Cierre')),
                ('estado_cierre', models.CharField(choices=[('CERRADA', 'CERRADA'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=10, verbose_name='Estado de Cierre')),
                ('evidencia_cierre', models.FileField(blank=True, null=True, upload_to='evidencias_reportes/', verbose_name='Archivo de Evidencia de Cierre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hora_creacion', models.TimeField(auto_now_add=True)),
                ('fecha_exportado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Exportación a PDF.')),
                ('hora_exportado', models.TimeField(blank=True, null=True, verbose_name='Hora de Exportación a PDF.')),
                ('nombre_usuario_creador', models.CharField(max_length=150, verbose_name='Usuario Creador')),
                ('correo_usuario_creador', models.EmailField(max_length=50, verbose_name='Correo Usuario Creador')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Reporte HSGI',
                'verbose_name_plural': 'Reportes HSGI',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.TextField()),
                ('counter', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReporteHSGIEvidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias_reporteshsgi/', verbose_name='Archivo de Evidencia')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('reporte_hsgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='app_reportes.reportehsgi', verbose_name='Evidencias de Reporte HSGI')),
            ],
            options={
                'verbose_name': 'Evidencia de Reporte HSGI',
                'verbose_name_plural': 'Evidencias de Reportes HSGI',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ItemObservacionConducta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(verbose_name='N°')),
                ('analisis_causa', models.TextField(verbose_name='Análisis de Causa')),
                ('acciones_correctivas', models.TextField(verbose_name='Acciones Correctivas')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('fecha_cumplimiento', models.DateField(verbose_name='Fecha')),
                ('cumplimiento', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=10, verbose_name='Estado de Cumplimiento')),
                ('observacion_conducta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_reportes.observacionconducta')),
            ],
            options={
                'verbose_name': 'Ítem de Observación de Conducta',
                'verbose_name_plural': 'Ítems de Observaciones de Conducta',
                'ordering': ['numero_item'],
            },
        ),
        migrations.CreateModel(
            name='ItemObsConductaEvidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias_obsconductas/', verbose_name='Archivo de Evidencia')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='app_reportes.itemobservacionconducta', verbose_name='Ítem de Observación de Conducta')),
            ],
            options={
                'verbose_name': 'Evidencia de Ítem (Observación de Conducta)',
                'verbose_name_plural': 'Evidencias de Ítems (Observaciones de Conducta)',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspeccionEvidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias_inspecciones/', verbose_name='Archivo de Evidencia')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='app_reportes.iteminspeccion', verbose_name='Ítem de Inspección')),
            ],
            options={
                'verbose_name': 'Evidencia de Ítem (Inspección)',
                'verbose_name_plural': 'Evidencias de Ítems (Inspecciones)',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
